// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1BGy8TKUhaGgfuFmT_3nJDA1Tu-EaRPk',
    appId: '1:812164604053:web:abc52977a7a6e8f5d2bb9c',
    messagingSenderId: '812164604053',
    projectId: 'workout-app-6b9b3',
    authDomain: 'workout-app-6b9b3.firebaseapp.com',
    storageBucket: 'workout-app-6b9b3.firebasestorage.app',
    measurementId: 'G-5HWKRTFJR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuzMMfZSl7S8i3b8YP6EWI8MgfPEM9HKA',
    appId: '1:812164604053:android:cefc0792d208149cd2bb9c',
    messagingSenderId: '812164604053',
    projectId: 'workout-app-6b9b3',
    storageBucket: 'workout-app-6b9b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpVmFq0RM9Q2KP5Vnll7Bj5NWJqFl3BNI',
    appId: '1:812164604053:ios:ff2e9e608333c2abd2bb9c',
    messagingSenderId: '812164604053',
    projectId: 'workout-app-6b9b3',
    storageBucket: 'workout-app-6b9b3.firebasestorage.app',
    iosBundleId: 'com.example.workout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpVmFq0RM9Q2KP5Vnll7Bj5NWJqFl3BNI',
    appId: '1:812164604053:ios:ff2e9e608333c2abd2bb9c',
    messagingSenderId: '812164604053',
    projectId: 'workout-app-6b9b3',
    storageBucket: 'workout-app-6b9b3.firebasestorage.app',
    iosBundleId: 'com.example.workout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1BGy8TKUhaGgfuFmT_3nJDA1Tu-EaRPk',
    appId: '1:812164604053:web:98fbe9601d67baf7d2bb9c',
    messagingSenderId: '812164604053',
    projectId: 'workout-app-6b9b3',
    authDomain: 'workout-app-6b9b3.firebaseapp.com',
    storageBucket: 'workout-app-6b9b3.firebasestorage.app',
    measurementId: 'G-TNWFLL5SW8',
  );

}